"""SAR Draft ORM model — Suspicious Activity Report lifecycle."""

from __future__ import annotations

from sqlalchemy import Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.domain.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class SARDraft(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """A Suspicious Activity Report draft.

    SARs are NEVER auto-filed. Every SAR requires human review and
    explicit approval. Edits create new versions — previous versions
    are preserved for audit purposes.
    """

    __tablename__ = "sar_drafts"

    entity_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    alert_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)

    # Lifecycle
    status: Mapped[str] = mapped_column(String(30), nullable=False, default="draft")
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1)

    # Content — generated by Reporter Agent, edited by human
    narrative: Mapped[str] = mapped_column(Text, nullable=False, default="")
    regulatory_basis: Mapped[str] = mapped_column(Text, nullable=False, default="")
    evidence_citations: Mapped[str] = mapped_column(Text, nullable=False, default="[]")
    risk_summary: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Entity snapshot at time of SAR generation
    entity_name: Mapped[str] = mapped_column(String(500), nullable=False, default="")
    entity_risk_score: Mapped[str] = mapped_column(String(20), nullable=False, default="0")
    entity_risk_band: Mapped[str] = mapped_column(String(20), nullable=False, default="low")

    # Human review
    reviewed_by: Mapped[str] = mapped_column(String(36), nullable=True)
    review_notes: Mapped[str] = mapped_column(Text, nullable=False, default="")
    decision: Mapped[str] = mapped_column(String(30), nullable=True)

    # Previous version reference (for edit chain)
    previous_version_id: Mapped[str] = mapped_column(String(36), nullable=True)

    # Relationship
    entity = relationship("Entity", back_populates="sar_drafts")

    __table_args__ = (
        Index("ix_sar_drafts_status", "status"),
        Index("ix_sar_drafts_entity_version", "entity_id", "version"),
    )
